[project]
name = "email-digest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
    "resend>=2.19.0",
    "supabase>=2.24.0",
]
